/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package adamasmacaswing;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Graphics2D;
import javax.swing.JOptionPane;

/**
 *
 * @author beyza
 */
public class AdamAsmaca extends javax.swing.JFrame {

    String kelime;
    String kelime2 = "";
    int can = 7;
    char harf;
    int harfSayisi;
    boolean oyunAktif = true;

    public AdamAsmaca() {
        initComponents();
        oyunaBasla();
    }

    private void oyunaBasla() {
        kelimeBelirle();
        for (int i = 0; i < kelime.length(); i++) {
            kelime2 += "_";
        }
        kelimeKutusu.setText(kelime2);
        canKutusu.setText(String.valueOf(can));

    }

    private void kelimeBelirle() {
        String[] sozluk = {"YAZILIM", "KODLAMA", "BILGISAYAR", "LAPTOP",
            "MUHENDISLIK", "PROGRAM", "PROGRAMLAMA", "ALGORITMA",
            "INTERNET", "VIRUS", "DEGISKEN", "BELLEK", "DERLEYICI"};
        int index = (int) (Math.random() * (8));
        kelime = sozluk[index];
    }

    private void harfSecildi(String kelime, char harf) {
        if (oyunAktif) {
            if (harfKelimedeVarMi()) {
                kelime2 = harfGoster(kelime2, kelime, harf);
            } else {
                can--;
            }
            canKutusu.setText(String.valueOf(can));
            adamCiz();
            kelimeKutusu.setText(kelime2);
            if (can == 0) {
                kaybettin();
            }
            if (kelime2.equals(kelime)) {
                kazandin();
            }
        }
    }

    private void kazandin() {
        oyunPanel.setVisible(false);
        bitisPanel.setVisible(true);
        sonuc.setText("KAZANDIN!");
        oyunAktif = false;
    }

    private void kaybettin() {
        oyunPanel.setVisible(false);
        bitisPanel.setVisible(true);
        sonuc.setText("GAME OVER!");
        oyunAktif = false;
        kelimeNeydi.setText("KELIME: " + kelime);
    }

    private static String harfGoster(String kelime, String Dogrukelime, char harf) {
        String kelime2 = "";
        for (int i = 0; i < kelime.length(); i++) {
            if (harf == Dogrukelime.charAt(i)) {
                kelime2 += harf;
            } else {
                kelime2 += kelime.charAt(i);
            }
        }
        return kelime2;
    }

    private boolean harfKelimedeVarMi() {
        harfSayisi = 0;
        for (int i = 0; i < kelime.length(); i++) {
            if (harf == kelime.charAt(i)) {
                harfSayisi++;
            }
        }
        return harfSayisi != 0;
    }

    private void adamCiz() {
        Graphics2D g2D = (Graphics2D) panelCopAdam.getGraphics();
        g2D.setColor(Color.BLACK);
        BasicStroke stroke = new BasicStroke(4);
        g2D.setStroke(stroke);
        if (can < 7) {
            g2D.drawLine(75, 25, 75, 45);
            g2D.drawLine(75, 25, 150, 25);
        }
        if (can < 6) {
            g2D.drawOval(50, 45, 50, 51);    //baş
        }
        if (can < 5) {
            g2D.drawLine(75, 96, 75, 147);   //gövde
        }
        if (can < 4) {
            g2D.drawLine(75, 98, 100, 145);  //kol1
        }
        if (can < 3) {
            g2D.drawLine(75, 98, 50, 145);   //kol2
        }
        if (can < 2) {
            g2D.drawLine(75, 147, 100, 198); //bacak1
            g2D.drawLine(100, 198, 112, 198);
        }
        if (can < 1) {
            g2D.drawLine(75, 147, 50, 198);  //bacak2
            g2D.drawLine(50, 198, 42, 198);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        enAltPanel = new javax.swing.JPanel();
        solPanel = new javax.swing.JPanel();
        oyunPanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        kelimeKutusu = new javax.swing.JLabel();
        klavyePanel = new javax.swing.JPanel();
        aButton = new adamasmacaswing.MyButton();
        bButton = new adamasmacaswing.MyButton();
        cButton = new adamasmacaswing.MyButton();
        dButton = new adamasmacaswing.MyButton();
        eButton = new adamasmacaswing.MyButton();
        fButton = new adamasmacaswing.MyButton();
        gButton = new adamasmacaswing.MyButton();
        hButton = new adamasmacaswing.MyButton();
        iButton = new adamasmacaswing.MyButton();
        jButton = new adamasmacaswing.MyButton();
        kButton = new adamasmacaswing.MyButton();
        lButton = new adamasmacaswing.MyButton();
        mButton = new adamasmacaswing.MyButton();
        nButton = new adamasmacaswing.MyButton();
        oButton = new adamasmacaswing.MyButton();
        pButton = new adamasmacaswing.MyButton();
        rButton = new adamasmacaswing.MyButton();
        sButton = new adamasmacaswing.MyButton();
        buldumButton = new adamasmacaswing.MyButton();
        zButton = new adamasmacaswing.MyButton();
        yButton = new adamasmacaswing.MyButton();
        vButton = new adamasmacaswing.MyButton();
        uButton = new adamasmacaswing.MyButton();
        tButton = new adamasmacaswing.MyButton();
        bitisPanel = new javax.swing.JPanel();
        sonuc = new javax.swing.JLabel();
        again = new adamasmacaswing.MyButton();
        kelimeNeydi = new javax.swing.JLabel();
        sagPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        canKutusu = new javax.swing.JLabel();
        panelCopAdam = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        enAltPanel.setBackground(new java.awt.Color(204, 255, 204));
        enAltPanel.setLayout(new javax.swing.BoxLayout(enAltPanel, javax.swing.BoxLayout.LINE_AXIS));

        solPanel.setPreferredSize(new java.awt.Dimension(500, 429));
        solPanel.setLayout(new java.awt.CardLayout());

        oyunPanel.setBackground(new java.awt.Color(51, 51, 51));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("KELİME:");

        kelimeKutusu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        kelimeKutusu.setForeground(new java.awt.Color(255, 255, 255));
        kelimeKutusu.setText("_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _");

        klavyePanel.setBackground(new java.awt.Color(255, 255, 255));

        aButton.setBackground(new java.awt.Color(102, 102, 102));
        aButton.setForeground(new java.awt.Color(255, 255, 255));
        aButton.setText("A");
        aButton.setColor(new java.awt.Color(102, 102, 102));
        aButton.setColorOver(new java.awt.Color(153, 153, 153));
        aButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                aButtonActionPerformed(evt);
            }
        });

        bButton.setBackground(new java.awt.Color(102, 102, 102));
        bButton.setForeground(new java.awt.Color(255, 255, 255));
        bButton.setText("B");
        bButton.setColor(new java.awt.Color(102, 102, 102));
        bButton.setColorOver(new java.awt.Color(153, 153, 153));
        bButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bButtonActionPerformed(evt);
            }
        });

        cButton.setBackground(new java.awt.Color(102, 102, 102));
        cButton.setForeground(new java.awt.Color(255, 255, 255));
        cButton.setText("C");
        cButton.setColor(new java.awt.Color(102, 102, 102));
        cButton.setColorOver(new java.awt.Color(153, 153, 153));
        cButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cButtonActionPerformed(evt);
            }
        });

        dButton.setBackground(new java.awt.Color(102, 102, 102));
        dButton.setForeground(new java.awt.Color(255, 255, 255));
        dButton.setText("D");
        dButton.setColor(new java.awt.Color(102, 102, 102));
        dButton.setColorOver(new java.awt.Color(153, 153, 153));
        dButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dButtonActionPerformed(evt);
            }
        });

        eButton.setBackground(new java.awt.Color(102, 102, 102));
        eButton.setForeground(new java.awt.Color(255, 255, 255));
        eButton.setText("E");
        eButton.setColor(new java.awt.Color(102, 102, 102));
        eButton.setColorOver(new java.awt.Color(153, 153, 153));
        eButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eButtonActionPerformed(evt);
            }
        });

        fButton.setBackground(new java.awt.Color(102, 102, 102));
        fButton.setForeground(new java.awt.Color(255, 255, 255));
        fButton.setText("F");
        fButton.setColor(new java.awt.Color(102, 102, 102));
        fButton.setColorOver(new java.awt.Color(153, 153, 153));
        fButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fButtonActionPerformed(evt);
            }
        });

        gButton.setBackground(new java.awt.Color(102, 102, 102));
        gButton.setForeground(new java.awt.Color(255, 255, 255));
        gButton.setText("G");
        gButton.setColor(new java.awt.Color(102, 102, 102));
        gButton.setColorOver(new java.awt.Color(153, 153, 153));
        gButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gButtonActionPerformed(evt);
            }
        });

        hButton.setBackground(new java.awt.Color(102, 102, 102));
        hButton.setForeground(new java.awt.Color(255, 255, 255));
        hButton.setText("H");
        hButton.setColor(new java.awt.Color(102, 102, 102));
        hButton.setColorOver(new java.awt.Color(153, 153, 153));
        hButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hButtonActionPerformed(evt);
            }
        });

        iButton.setBackground(new java.awt.Color(102, 102, 102));
        iButton.setForeground(new java.awt.Color(255, 255, 255));
        iButton.setText("I");
        iButton.setColor(new java.awt.Color(102, 102, 102));
        iButton.setColorOver(new java.awt.Color(153, 153, 153));
        iButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iButtonActionPerformed(evt);
            }
        });

        jButton.setBackground(new java.awt.Color(102, 102, 102));
        jButton.setForeground(new java.awt.Color(255, 255, 255));
        jButton.setText("J");
        jButton.setColor(new java.awt.Color(102, 102, 102));
        jButton.setColorOver(new java.awt.Color(153, 153, 153));
        jButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonActionPerformed(evt);
            }
        });

        kButton.setBackground(new java.awt.Color(102, 102, 102));
        kButton.setForeground(new java.awt.Color(255, 255, 255));
        kButton.setText("K");
        kButton.setColor(new java.awt.Color(102, 102, 102));
        kButton.setColorOver(new java.awt.Color(153, 153, 153));
        kButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButtonActionPerformed(evt);
            }
        });

        lButton.setBackground(new java.awt.Color(102, 102, 102));
        lButton.setForeground(new java.awt.Color(255, 255, 255));
        lButton.setText("L");
        lButton.setColor(new java.awt.Color(102, 102, 102));
        lButton.setColorOver(new java.awt.Color(153, 153, 153));
        lButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lButtonActionPerformed(evt);
            }
        });

        mButton.setBackground(new java.awt.Color(102, 102, 102));
        mButton.setForeground(new java.awt.Color(255, 255, 255));
        mButton.setText("M");
        mButton.setColor(new java.awt.Color(102, 102, 102));
        mButton.setColorOver(new java.awt.Color(153, 153, 153));
        mButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mButtonActionPerformed(evt);
            }
        });

        nButton.setBackground(new java.awt.Color(102, 102, 102));
        nButton.setForeground(new java.awt.Color(255, 255, 255));
        nButton.setText("N");
        nButton.setColor(new java.awt.Color(102, 102, 102));
        nButton.setColorOver(new java.awt.Color(153, 153, 153));
        nButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nButtonActionPerformed(evt);
            }
        });

        oButton.setBackground(new java.awt.Color(102, 102, 102));
        oButton.setForeground(new java.awt.Color(255, 255, 255));
        oButton.setText("O");
        oButton.setColor(new java.awt.Color(102, 102, 102));
        oButton.setColorOver(new java.awt.Color(153, 153, 153));
        oButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                oButtonActionPerformed(evt);
            }
        });

        pButton.setBackground(new java.awt.Color(102, 102, 102));
        pButton.setForeground(new java.awt.Color(255, 255, 255));
        pButton.setText("P");
        pButton.setColor(new java.awt.Color(102, 102, 102));
        pButton.setColorOver(new java.awt.Color(153, 153, 153));
        pButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pButtonActionPerformed(evt);
            }
        });

        rButton.setBackground(new java.awt.Color(102, 102, 102));
        rButton.setForeground(new java.awt.Color(255, 255, 255));
        rButton.setText("R");
        rButton.setColor(new java.awt.Color(102, 102, 102));
        rButton.setColorOver(new java.awt.Color(153, 153, 153));
        rButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rButtonActionPerformed(evt);
            }
        });

        sButton.setBackground(new java.awt.Color(102, 102, 102));
        sButton.setForeground(new java.awt.Color(255, 255, 255));
        sButton.setText("S");
        sButton.setColor(new java.awt.Color(102, 102, 102));
        sButton.setColorOver(new java.awt.Color(153, 153, 153));
        sButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sButtonActionPerformed(evt);
            }
        });

        buldumButton.setBackground(new java.awt.Color(102, 102, 102));
        buldumButton.setForeground(new java.awt.Color(255, 255, 255));
        buldumButton.setText("BULDUM");
        buldumButton.setColor(new java.awt.Color(102, 102, 102));
        buldumButton.setColorOver(new java.awt.Color(153, 153, 153));
        buldumButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buldumButtonActionPerformed(evt);
            }
        });

        zButton.setBackground(new java.awt.Color(102, 102, 102));
        zButton.setForeground(new java.awt.Color(255, 255, 255));
        zButton.setText("Z");
        zButton.setColor(new java.awt.Color(102, 102, 102));
        zButton.setColorOver(new java.awt.Color(153, 153, 153));
        zButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                zButtonActionPerformed(evt);
            }
        });

        yButton.setBackground(new java.awt.Color(102, 102, 102));
        yButton.setForeground(new java.awt.Color(255, 255, 255));
        yButton.setText("Y");
        yButton.setColor(new java.awt.Color(102, 102, 102));
        yButton.setColorOver(new java.awt.Color(153, 153, 153));
        yButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yButtonActionPerformed(evt);
            }
        });

        vButton.setBackground(new java.awt.Color(102, 102, 102));
        vButton.setForeground(new java.awt.Color(255, 255, 255));
        vButton.setText("V");
        vButton.setColor(new java.awt.Color(102, 102, 102));
        vButton.setColorOver(new java.awt.Color(153, 153, 153));
        vButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                vButtonActionPerformed(evt);
            }
        });

        uButton.setBackground(new java.awt.Color(102, 102, 102));
        uButton.setForeground(new java.awt.Color(255, 255, 255));
        uButton.setText("U");
        uButton.setColor(new java.awt.Color(102, 102, 102));
        uButton.setColorOver(new java.awt.Color(153, 153, 153));
        uButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uButtonActionPerformed(evt);
            }
        });

        tButton.setBackground(new java.awt.Color(102, 102, 102));
        tButton.setForeground(new java.awt.Color(255, 255, 255));
        tButton.setText("T");
        tButton.setColor(new java.awt.Color(102, 102, 102));
        tButton.setColorOver(new java.awt.Color(153, 153, 153));
        tButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout klavyePanelLayout = new javax.swing.GroupLayout(klavyePanel);
        klavyePanel.setLayout(klavyePanelLayout);
        klavyePanelLayout.setHorizontalGroup(
            klavyePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(klavyePanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(klavyePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, klavyePanelLayout.createSequentialGroup()
                        .addComponent(tButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(uButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(vButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(yButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(zButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buldumButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, klavyePanelLayout.createSequentialGroup()
                        .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(mButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(nButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(oButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(pButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(rButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(sButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, klavyePanelLayout.createSequentialGroup()
                        .addComponent(aButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(dButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(eButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(fButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(gButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(iButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(20, Short.MAX_VALUE))
        );
        klavyePanelLayout.setVerticalGroup(
            klavyePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(klavyePanelLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(klavyePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(eButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(hButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(iButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(klavyePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(klavyePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(uButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(vButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(zButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buldumButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout oyunPanelLayout = new javax.swing.GroupLayout(oyunPanel);
        oyunPanel.setLayout(oyunPanelLayout);
        oyunPanelLayout.setHorizontalGroup(
            oyunPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oyunPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(oyunPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kelimeKutusu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(klavyePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(176, 176, 176))
        );
        oyunPanelLayout.setVerticalGroup(
            oyunPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(oyunPanelLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(kelimeKutusu)
                .addGap(59, 59, 59)
                .addComponent(klavyePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(144, 144, 144))
        );

        solPanel.add(oyunPanel, "card3");

        bitisPanel.setBackground(new java.awt.Color(51, 51, 51));

        sonuc.setFont(new java.awt.Font("HYMyeongJo-Extra", 1, 36)); // NOI18N
        sonuc.setForeground(new java.awt.Color(204, 0, 0));
        sonuc.setText("GAME OVER");

        again.setText("AGAIN");
        again.setBorderColor(new java.awt.Color(0, 0, 0));
        again.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        again.setRadius(30);
        again.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                againActionPerformed(evt);
            }
        });

        kelimeNeydi.setFont(new java.awt.Font("HYMyeongJo-Extra", 1, 18)); // NOI18N
        kelimeNeydi.setForeground(new java.awt.Color(204, 204, 204));
        kelimeNeydi.setText("  ");

        javax.swing.GroupLayout bitisPanelLayout = new javax.swing.GroupLayout(bitisPanel);
        bitisPanel.setLayout(bitisPanelLayout);
        bitisPanelLayout.setHorizontalGroup(
            bitisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bitisPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(sonuc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(bitisPanelLayout.createSequentialGroup()
                .addGap(181, 181, 181)
                .addComponent(again, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
            .addGroup(bitisPanelLayout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(kelimeNeydi, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        bitisPanelLayout.setVerticalGroup(
            bitisPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bitisPanelLayout.createSequentialGroup()
                .addGap(148, 148, 148)
                .addComponent(sonuc, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(again, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(kelimeNeydi, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(230, Short.MAX_VALUE))
        );

        solPanel.add(bitisPanel, "card2");

        enAltPanel.add(solPanel);

        sagPanel.setBackground(new java.awt.Color(102, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("CAN:");

        canKutusu.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        javax.swing.GroupLayout panelCopAdamLayout = new javax.swing.GroupLayout(panelCopAdam);
        panelCopAdam.setLayout(panelCopAdamLayout);
        panelCopAdamLayout.setHorizontalGroup(
            panelCopAdamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        panelCopAdamLayout.setVerticalGroup(
            panelCopAdamLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 245, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout sagPanelLayout = new javax.swing.GroupLayout(sagPanel);
        sagPanel.setLayout(sagPanelLayout);
        sagPanelLayout.setHorizontalGroup(
            sagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sagPanelLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(sagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sagPanelLayout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(canKutusu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, sagPanelLayout.createSequentialGroup()
                        .addComponent(panelCopAdam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))))
        );
        sagPanelLayout.setVerticalGroup(
            sagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sagPanelLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(sagPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(canKutusu, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addComponent(panelCopAdam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(202, Short.MAX_VALUE))
        );

        enAltPanel.add(sagPanel);

        getContentPane().add(enAltPanel);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void aButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_aButtonActionPerformed
        harf = aButton.getText().charAt(0);
        harfSecildi(kelime, harf);
        aButton.setEnabled(false);
    }//GEN-LAST:event_aButtonActionPerformed

    private void bButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bButtonActionPerformed
        harf = bButton.getText().charAt(0);
        harfSecildi(kelime, harf);
        bButton.setEnabled(false);
    }//GEN-LAST:event_bButtonActionPerformed

    private void cButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cButtonActionPerformed
        harf = cButton.getText().charAt(0);
        harfSecildi(kelime, harf);
        cButton.setEnabled(false);
    }//GEN-LAST:event_cButtonActionPerformed

    private void dButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dButtonActionPerformed
        harf = dButton.getText().charAt(0);
        harfSecildi(kelime, harf);
        dButton.setEnabled(false);
    }//GEN-LAST:event_dButtonActionPerformed

    private void eButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eButtonActionPerformed
        harf = eButton.getText().charAt(0);
        harfSecildi(kelime, harf);
        eButton.setEnabled(false);
    }//GEN-LAST:event_eButtonActionPerformed

    private void fButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fButtonActionPerformed
        harf = fButton.getText().charAt(0);
        harfSecildi(kelime, harf);
        fButton.setEnabled(false);
    }//GEN-LAST:event_fButtonActionPerformed

    private void gButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gButtonActionPerformed
        harf = gButton.getText().charAt(0);
        harfSecildi(kelime, harf);
        gButton.setEnabled(false);
    }//GEN-LAST:event_gButtonActionPerformed

    private void hButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hButtonActionPerformed
        harf = hButton.getText().charAt(0);
        harfSecildi(kelime, harf);
        hButton.setEnabled(false);
    }//GEN-LAST:event_hButtonActionPerformed

    private void iButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_iButtonActionPerformed
        harf = iButton.getText().charAt(0);
        harfSecildi(kelime, harf);
        iButton.setEnabled(false);
    }//GEN-LAST:event_iButtonActionPerformed

    private void jButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonActionPerformed
        harf = jButton.getText().charAt(0);
        harfSecildi(kelime, harf);
        jButton.setEnabled(false);
    }//GEN-LAST:event_jButtonActionPerformed

    private void kButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButtonActionPerformed
        harf = kButton.getText().charAt(0);
        harfSecildi(kelime, harf);
        kButton.setEnabled(false);
    }//GEN-LAST:event_kButtonActionPerformed

    private void lButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lButtonActionPerformed
        harf = lButton.getText().charAt(0);
        harfSecildi(kelime, harf);
        lButton.setEnabled(false);
    }//GEN-LAST:event_lButtonActionPerformed

    private void mButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mButtonActionPerformed
        harf = mButton.getText().charAt(0);
        harfSecildi(kelime, harf);
        mButton.setEnabled(false);
    }//GEN-LAST:event_mButtonActionPerformed

    private void nButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nButtonActionPerformed
        harf = nButton.getText().charAt(0);
        harfSecildi(kelime, harf);
        nButton.setEnabled(false);
    }//GEN-LAST:event_nButtonActionPerformed

    private void oButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_oButtonActionPerformed
        harf = oButton.getText().charAt(0);
        harfSecildi(kelime, harf);
        oButton.setEnabled(false);
    }//GEN-LAST:event_oButtonActionPerformed

    private void pButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pButtonActionPerformed
        harf = pButton.getText().charAt(0);
        harfSecildi(kelime, harf);
        pButton.setEnabled(false);
    }//GEN-LAST:event_pButtonActionPerformed

    private void rButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rButtonActionPerformed
        harf = rButton.getText().charAt(0);
        harfSecildi(kelime, harf);
        rButton.setEnabled(false);
    }//GEN-LAST:event_rButtonActionPerformed

    private void sButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sButtonActionPerformed
        harf = sButton.getText().charAt(0);
        harfSecildi(kelime, harf);
        sButton.setEnabled(false);
    }//GEN-LAST:event_sButtonActionPerformed

    private void zButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_zButtonActionPerformed
        harf = zButton.getText().charAt(0);
        harfSecildi(kelime, harf);
        zButton.setEnabled(false);
    }//GEN-LAST:event_zButtonActionPerformed

    private void yButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yButtonActionPerformed
        harf = yButton.getText().charAt(0);
        harfSecildi(kelime, harf);
        yButton.setEnabled(false);
    }//GEN-LAST:event_yButtonActionPerformed

    private void vButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_vButtonActionPerformed
        harf = vButton.getText().charAt(0);
        harfSecildi(kelime, harf);
        vButton.setEnabled(false);
    }//GEN-LAST:event_vButtonActionPerformed

    private void uButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uButtonActionPerformed
        harf = uButton.getText().charAt(0);
        harfSecildi(kelime, harf);
        uButton.setEnabled(false);
    }//GEN-LAST:event_uButtonActionPerformed

    private void tButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tButtonActionPerformed
        harf = tButton.getText().charAt(0);
        harfSecildi(kelime, harf);
        tButton.setEnabled(false);
    }//GEN-LAST:event_tButtonActionPerformed

    private void buldumButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buldumButtonActionPerformed
        String cevap = JOptionPane.showInputDialog(rootPane, "Kelimeyi Giriniz.",
                "KELIME", JOptionPane.INFORMATION_MESSAGE);
        if (cevap.equals(kelime)) {
            kazandin();
        } else {
            kaybettin();
            can = 0;
            adamCiz();
        }
        buldumButton.setEnabled(false);
    }//GEN-LAST:event_buldumButtonActionPerformed

    private void againActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_againActionPerformed
        this.dispose();
        new AdamAsmaca().setVisible(true);
    }//GEN-LAST:event_againActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdamAsmaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdamAsmaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdamAsmaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdamAsmaca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdamAsmaca().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private adamasmacaswing.MyButton aButton;
    private adamasmacaswing.MyButton again;
    private adamasmacaswing.MyButton bButton;
    private javax.swing.JPanel bitisPanel;
    private adamasmacaswing.MyButton buldumButton;
    private adamasmacaswing.MyButton cButton;
    private javax.swing.JLabel canKutusu;
    private adamasmacaswing.MyButton dButton;
    private adamasmacaswing.MyButton eButton;
    private javax.swing.JPanel enAltPanel;
    private adamasmacaswing.MyButton fButton;
    private adamasmacaswing.MyButton gButton;
    private adamasmacaswing.MyButton hButton;
    private adamasmacaswing.MyButton iButton;
    private adamasmacaswing.MyButton jButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private adamasmacaswing.MyButton kButton;
    private javax.swing.JLabel kelimeKutusu;
    private javax.swing.JLabel kelimeNeydi;
    private javax.swing.JPanel klavyePanel;
    private adamasmacaswing.MyButton lButton;
    private adamasmacaswing.MyButton mButton;
    private adamasmacaswing.MyButton nButton;
    private adamasmacaswing.MyButton oButton;
    private javax.swing.JPanel oyunPanel;
    private adamasmacaswing.MyButton pButton;
    private javax.swing.JPanel panelCopAdam;
    private adamasmacaswing.MyButton rButton;
    private adamasmacaswing.MyButton sButton;
    private javax.swing.JPanel sagPanel;
    private javax.swing.JPanel solPanel;
    private javax.swing.JLabel sonuc;
    private adamasmacaswing.MyButton tButton;
    private adamasmacaswing.MyButton uButton;
    private adamasmacaswing.MyButton vButton;
    private adamasmacaswing.MyButton yButton;
    private adamasmacaswing.MyButton zButton;
    // End of variables declaration//GEN-END:variables
}
